export type TypographyVariants =
  | 'title'
  | 'largeTitle'
  | 'subtitle1'
  | 'subtitle2'
  | 'body20'
  | 'body17Medium'
  | 'body17Regular'
  | 'body15Regular'
  | 'body15Semibold'
  | 'caption1'
  | 'caption2'
  | 'caption3'
  | 'caption4'
  | 'button';
